export const MAIN_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const LANGUAGES_ROUTE = '/languages'
export const STACKS_ROUTE = '/stacks'
export const ROLES_ROUTE = '/roles'
export const INTERVIEW_REPORT = '/interview/report'