//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../api-client.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './TeacherClient'
export { Client };
import type { AxiosRequestConfig } from 'axios';

export type GetAllTeachersTeacherQueryParameters = {
  page?: number | undefined ;
  size?: number | undefined ;
  sort?: string[] | undefined ;
  fullName?: string | undefined ;
}

export function createTeacherUrl(): string {
  let url_ = getBaseUrl() + "/api/v1/teacher";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function createTeacherMutationKey(): MutationKey {
  return trimArrayEnd([
      'TeacherClient',
      'createTeacher',
    ]);
}

/**
 * Создание преподавателя
 * @return OK
 */
export function useCreateTeacherMutation<TContext>(options?: Omit<UseMutationOptions<Types.TeacherDto, unknown, Types.TeacherCreateDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.TeacherDto, unknown, Types.TeacherCreateDto, TContext> {
  const key = createTeacherMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (body: Types.TeacherCreateDto) => Client.createTeacher(body),
    mutationKey: key,
  });
}
  
export function getAllTeachersUrl(page?: number | undefined, size?: number | undefined, sort?: string[] | undefined, fullName?: string | undefined): string {
  let url_ = getBaseUrl() + "/api/v1/teacher/list?";
if (page === null)
    throw new Error("The parameter 'page' cannot be null.");
else if (page !== undefined)
    url_ += "page=" + encodeURIComponent("" + page) + "&";
if (size === null)
    throw new Error("The parameter 'size' cannot be null.");
else if (size !== undefined)
    url_ += "size=" + encodeURIComponent("" + size) + "&";
if (sort === null)
    throw new Error("The parameter 'sort' cannot be null.");
else if (sort !== undefined)
    sort && sort.forEach(item => { url_ += "sort=" + encodeURIComponent("" + item) + "&"; });
if (fullName === null)
    throw new Error("The parameter 'fullName' cannot be null.");
else if (fullName !== undefined)
    url_ += "fullName=" + encodeURIComponent("" + fullName) + "&";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let getAllTeachersDefaultOptions: Omit<UseQueryOptions<Types.PagedListDtoTeacherDto, unknown, Types.PagedListDtoTeacherDto>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<Types.PagedListDtoTeacherDto, unknown, Types.PagedListDtoTeacherDto>, 'queryFn'>> = {
};
export function getGetAllTeachersDefaultOptions() {
  return getAllTeachersDefaultOptions;
};
export function setGetAllTeachersDefaultOptions(options: typeof getAllTeachersDefaultOptions) {
  getAllTeachersDefaultOptions = options;
}

export function getAllTeachersQueryKey(dto: GetAllTeachersTeacherQueryParameters): QueryKey;
export function getAllTeachersQueryKey(page?: number | undefined, size?: number | undefined, sort?: string[] | undefined, fullName?: string | undefined): QueryKey;
export function getAllTeachersQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { page, size, sort, fullName,  } = params[0] as GetAllTeachersTeacherQueryParameters;

    return trimArrayEnd([
        'TeacherClient',
        'getAllTeachers',
        page as any,
        size as any,
        sort as any,
        fullName as any,
      ]);
  } else {
    return trimArrayEnd([
        'TeacherClient',
        'getAllTeachers',
        ...params
      ]);
  }
}
export function __getAllTeachers(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client.getAllTeachers(
      context.queryKey[2] as number | undefined,       context.queryKey[3] as number | undefined,       context.queryKey[4] as string[] | undefined,       context.queryKey[5] as string | undefined,axiosConfig    );
}

export function useGetAllTeachersQuery<TSelectData = Types.PagedListDtoTeacherDto, TError = unknown>(dto: GetAllTeachersTeacherQueryParameters, options?: Omit<UseQueryOptions<Types.PagedListDtoTeacherDto, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
/**
 * Получение всех преподавателей
 * @param page (optional) Zero-based page index (0..N)
 * @param size (optional) The size of the page to be returned
 * @param sort (optional) Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 * @param fullName (optional) 
 * @return OK
 */
export function useGetAllTeachersQuery<TSelectData = Types.PagedListDtoTeacherDto, TError = unknown>(page?: number | undefined, size?: number | undefined, sort?: string[] | undefined, fullName?: string | undefined, options?: Omit<UseQueryOptions<Types.PagedListDtoTeacherDto, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useGetAllTeachersQuery<TSelectData = Types.PagedListDtoTeacherDto, TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.PagedListDtoTeacherDto, TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  let page: any = undefined;
  let size: any = undefined;
  let sort: any = undefined;
  let fullName: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ page, size, sort, fullName,  } = params[0] as GetAllTeachersTeacherQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [page, size, sort, fullName, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<Types.PagedListDtoTeacherDto, TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __getAllTeachers(context, axiosConfig) : __getAllTeachers,
    queryKey: getAllTeachersQueryKey(page, size, sort, fullName),
    ...getAllTeachersDefaultOptions as unknown as Omit<UseQueryOptions<Types.PagedListDtoTeacherDto, TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}
/**
 * Получение всех преподавателей
 * @param page (optional) Zero-based page index (0..N)
 * @param size (optional) The size of the page to be returned
 * @param sort (optional) Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 * @param fullName (optional) 
 * @return OK
 */
export function setGetAllTeachersData(queryClient: QueryClient, updater: (data: Types.PagedListDtoTeacherDto | undefined) => Types.PagedListDtoTeacherDto, page?: number | undefined, size?: number | undefined, sort?: string[] | undefined, fullName?: string | undefined) {
  queryClient.setQueryData(getAllTeachersQueryKey(page, size, sort, fullName),
    updater
  );
}

/**
 * Получение всех преподавателей
 * @param page (optional) Zero-based page index (0..N)
 * @param size (optional) The size of the page to be returned
 * @param sort (optional) Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 * @param fullName (optional) 
 * @return OK
 */
export function setGetAllTeachersDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.PagedListDtoTeacherDto | undefined) => Types.PagedListDtoTeacherDto) {
  queryClient.setQueryData(queryKey, updater);
}